function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "SubSystemCalc"};
	this.sidHashMap["SubSystemCalc"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "SubSystemCalc:11"};
	this.sidHashMap["SubSystemCalc:11"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "SubSystemCalc:1"};
	this.sidHashMap["SubSystemCalc:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/In2"] = {sid: "SubSystemCalc:2"};
	this.sidHashMap["SubSystemCalc:2"] = {rtwname: "<Root>/In2"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "SubSystemCalc:11"};
	this.sidHashMap["SubSystemCalc:11"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "SubSystemCalc:7"};
	this.sidHashMap["SubSystemCalc:7"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<Root>/Out2"] = {sid: "SubSystemCalc:8"};
	this.sidHashMap["SubSystemCalc:8"] = {rtwname: "<Root>/Out2"};
	this.rtwnameHashMap["<Root>/Out3"] = {sid: "SubSystemCalc:9"};
	this.sidHashMap["SubSystemCalc:9"] = {rtwname: "<Root>/Out3"};
	this.rtwnameHashMap["<Root>/Out4"] = {sid: "SubSystemCalc:10"};
	this.sidHashMap["SubSystemCalc:10"] = {rtwname: "<Root>/Out4"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "SubSystemCalc:12"};
	this.sidHashMap["SubSystemCalc:12"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/In2"] = {sid: "SubSystemCalc:13"};
	this.sidHashMap["SubSystemCalc:13"] = {rtwname: "<S1>/In2"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "SubSystemCalc:3"};
	this.sidHashMap["SubSystemCalc:3"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Divide"] = {sid: "SubSystemCalc:4"};
	this.sidHashMap["SubSystemCalc:4"] = {rtwname: "<S1>/Divide"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "SubSystemCalc:5"};
	this.sidHashMap["SubSystemCalc:5"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Subtract"] = {sid: "SubSystemCalc:6"};
	this.sidHashMap["SubSystemCalc:6"] = {rtwname: "<S1>/Subtract"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "SubSystemCalc:14"};
	this.sidHashMap["SubSystemCalc:14"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S1>/Out2"] = {sid: "SubSystemCalc:15"};
	this.sidHashMap["SubSystemCalc:15"] = {rtwname: "<S1>/Out2"};
	this.rtwnameHashMap["<S1>/Out3"] = {sid: "SubSystemCalc:16"};
	this.sidHashMap["SubSystemCalc:16"] = {rtwname: "<S1>/Out3"};
	this.rtwnameHashMap["<S1>/Out4"] = {sid: "SubSystemCalc:17"};
	this.sidHashMap["SubSystemCalc:17"] = {rtwname: "<S1>/Out4"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
